name: Ruff lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/**.py
      - check.py
      - run.py
      - update.py
      - .github/workflows/pyright.yml
  pull_request:
    branches:
      - main
    paths:
      - api/**.py
      - check.py
      - run.py
      - update.py
      - .github/workflows/pyright.yml

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ruff lint
        uses: astral-sh/ruff-action@v3
